yahoo_redirect_uri: "https://localhost"
yahoo_team_url: "https://fantasysports.yahooapis.com/fantasy/v2/team/"
yahoo_league_url: "https://fantasysports.yahooapis.com/fantasy/v2/league/"

# Sarcus Mmart
# yahoo_year_id: "418"
# yahoo_league_id: "33024"
# yahoo_team_id: "4"

# mxm
# yahoo_year_id: "418"
# yahoo_league_id: "33024"
# yahoo_team_id: "1"

# Different animal same brow
# yahoo_year_id: "418"
# yahoo_league_id: "33024"
# yahoo_team_id: "2"

# Boston Lakers
# yahoo_year_id: "418"
# yahoo_league_id: "33024"
# yahoo_team_id: "3"

# Livin' La Vida Luka
# yahoo_year_id: "418"
# yahoo_league_id: "33024"
# yahoo_team_id: "5"

# Sascal Piakam
yahoo_team_name: "Sascal Piakam"
yahoo_year_id: "418"
yahoo_league_id: "117259"
yahoo_team_id: "1"

# IL. Ball
# yahoo_year_id: "418"
# yahoo_league_id: "117259"
# yahoo_team_id: "2"

# Aam Bdebayo
# yahoo_year_id: "410"
# yahoo_league_id: "129496"
# yahoo_team_id: "1"